"""consistency_gate.py -- cross-surface numeric agreement for SMN articles.

Every existing gate checks ONE surface in isolation. citation_gate checks
citations, integrity_gate scans prose and deliberately strips server-rendered
chrome because chrome is "correct by construction". That assumption is the hole:
chrome is generated by code, code has bugs, and nothing was verifying it.

Two production defects found on 2026-08-17 lived entirely inside that hole:

  * A bearish Ford window that fell in 9 of 10 years rendered its cumulative
    chart caption as "compounds to +61.0%". The number was right -- it is the
    SHORT side -- and the caption never said so. Every bearish article SMN has
    published carries a large positive cumulative figure beside prose about a
    security that fell.
  * The same article's two chart captions read "9 of the past 9 years" and
    "10 of the past 10 years", while the key-stats box said 10 years / 0
    winners / 9 losers and the prose said "9 of 10".

Neither is a fabrication, so no fabrication check fires. Each surface is
internally coherent, so no single-surface check fires. They only disagree with
each other.

This module extracts every numeric claim from every surface and asserts they
describe the same reality. It is pure stdlib and makes no model call.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional, Tuple

_TAG = re.compile(r"<[^>]+>")
_FIGCAPTION = re.compile(r"<figcaption[^>]*>(.*?)</figcaption>", re.I | re.S)
_KEYSTATS = re.compile(
    r'<aside[^>]*class="[^"]*key-stats[^"]*"[^>]*>(.*?)</aside>', re.I | re.S)
_SOURCES = re.compile(
    r'<section[^>]*class="[^"]*\bsources\b[^"]*"[^>]*>(.*?)</section>',
    re.I | re.S)

# "closed higher in 14 of the last 20 years", "9 of 10", "14 of 20 years"
_X_OF_Y = re.compile(
    r"\b(\d{1,3})\s*(?:of|for|out of)\s*(?:the\s+)?(?:last\s+|past\s+)?(\d{1,3})\b",
    re.I)
_N_EQUALS = re.compile(r"\bn\s*=\s*(\d{1,3})\b", re.I)
_COMPOUNDS = re.compile(
    r"compounds?\s+to\s+([+-]?\d+(?:\.\d+)?)\s*%", re.I)
_LABELLED = re.compile(
    r"(Num Winners|Num Losers|Sample Size|Percent Profitable)\D{0,40}?"
    r"(\d{1,3}(?:\.\d+)?)", re.I)
_SHORT_WORDS = re.compile(r"\bshort(?:ing|-side)?\b", re.I)
_FELL_WORDS = re.compile(
    r"\b(closed lower|fell|declin\w+|bearish|weak\w*|negative)\b", re.I)


def _text(html: str) -> str:
    return re.sub(r"\s+", " ", _TAG.sub(" ", html or "")).strip()


def _issue(out: List[Dict[str, str]], code: str, detail: str) -> None:
    out.append({"code": code, "detail": detail})


def _surfaces(html: str) -> Dict[str, Any]:
    """Split an article into the surfaces that carry numbers."""
    caps = [_text(c) for c in _FIGCAPTION.findall(html or "")]
    ks = _KEYSTATS.search(html or "")
    keystats = _text(ks.group(1)) if ks else ""
    body = _SOURCES.sub(" ", html or "")
    body = _FIGCAPTION.sub(" ", body)
    if ks:
        body = body.replace(ks.group(0), " ")
    return {"captions": caps, "keystats": keystats, "prose": _text(body)}


def _labelled_stats(keystats: str) -> Dict[str, float]:
    out: Dict[str, float] = {}
    for label, value in _LABELLED.findall(keystats or ""):
        try:
            out[label.lower()] = float(value)
        except ValueError:
            continue
    return out


def check_article(html: str, *, direction: Optional[str] = None) -> Dict[str, Any]:
    """Return {'ok', 'errors', 'warnings', 'observed'} for one article.

    `direction` is the pattern's true trade direction when the caller knows it
    ('long' | 'short'). Derive it from per-year net returns, never from
    ChartData4's Trade Dir field, which reports 'long' on arbitrary windows.
    """
    errors: List[Dict[str, str]] = []
    warnings: List[Dict[str, str]] = []
    if not html:
        return {"ok": True, "errors": [], "warnings": [], "observed": {}}

    s = _surfaces(html)
    stats = _labelled_stats(s["keystats"])
    observed: Dict[str, Any] = {"stats": stats}

    # ---- 1. winners + losers must not exceed the stated sample -----------
    n = stats.get("sample size")
    wins, losses = stats.get("num winners"), stats.get("num losers")
    if n is not None and wins is not None and losses is not None:
        if wins + losses > n:
            _issue(errors, "STATS_SUM_EXCEEDS_SAMPLE",
                   f"{wins:.0f} winners + {losses:.0f} losers > sample {n:.0f}")
        elif wins + losses < n:
            warnings.append({
                "code": "STATS_SUM_BELOW_SAMPLE",
                "detail": (f"{wins:.0f}+{losses:.0f} < sample {n:.0f}; "
                           f"{n - wins - losses:.0f} year(s) neither won nor "
                           f"lost -- a flat/zeroed row is the usual cause")})

    # ---- 2. every "X of Y" across every surface must share one Y --------
    denominators: Dict[int, List[str]] = {}
    for surface in ("prose", "keystats"):
        for _, y in _X_OF_Y.findall(s[surface]):
            denominators.setdefault(int(y), []).append(surface)
    for cap in s["captions"]:
        for _, y in _X_OF_Y.findall(cap):
            denominators.setdefault(int(y), []).append("caption")
        for y in _N_EQUALS.findall(cap):
            denominators.setdefault(int(y), []).append("caption n=")
    observed["denominators"] = {k: sorted(set(v)) for k, v in denominators.items()}
    # An article may legitimately cite more than one sample: the story cell
    # plus an auxiliary cell (Ford's 10 midterm years against 20 years of full
    # history) is the FORK/REGIME comparison the angle engine exists to make.
    # So multiple denominators in PROSE are fine. Chart captions are not --
    # each caption describes one rendered chart of the story cell, and two
    # captions in the same article claiming different sample sizes for the
    # same window is a rendering bug, not an editorial choice.
    caption_ns: Dict[int, int] = {}
    for cap in s["captions"]:
        for y in _N_EQUALS.findall(cap):
            caption_ns[int(y)] = caption_ns.get(int(y), 0) + 1
        for _, y in _X_OF_Y.findall(cap):
            caption_ns[int(y)] = caption_ns.get(int(y), 0) + 1
    observed["caption_samples"] = caption_ns
    if len(caption_ns) > 1:
        _issue(errors, "CAPTION_SAMPLE_DISAGREEMENT",
               f"chart captions state different sample sizes for the same "
               f"window: {sorted(caption_ns)}")

    # ---- 3. captions must agree with the authoritative key-stats sample --
    if n is not None and caption_ns and int(n) not in caption_ns:
        _issue(errors, "CAPTION_SAMPLE_NOT_KEYSTATS",
               f"key-stats says {n:.0f} years, captions say "
               f"{sorted(caption_ns)}")
    if n is not None and len(denominators) > 1 and int(n) not in denominators:
        warnings.append({
            "code": "SAMPLE_NOT_IN_PROSE",
            "detail": (f"key-stats sample {n:.0f} never appears in prose; "
                       f"prose uses {sorted(denominators)}")})

    # ---- 3b. caption COUNTS must match the labelled winner/loser counts --
    # Denominator agreement is not enough. After the sample-size fix above,
    # Ford's captions agreed at "10 of the past 10 years" while the key-stats
    # box beside them said 9 losers -- the flat year had been folded into the
    # loss column by deriving losses as n - wins instead of counting them.
    for cap in s["captions"]:
        low = cap.lower()
        if "closed lower" in low:
            expected = losses
        elif "closed higher" in low:
            expected = wins
        else:
            continue
        if expected is None:
            continue
        for k, y in _X_OF_Y.findall(cap):
            if int(y) == int(n or 0) and int(k) != int(expected):
                _issue(errors, "CAPTION_COUNT_MISMATCH",
                       f"caption says {k} of {y} but key-stats says "
                       f"{expected:.0f} ({'losers' if 'lower' in low else 'winners'})")

    # ---- 4. a positive cumulative on a falling security must say SHORT --
    for cap in s["captions"]:
        m = _COMPOUNDS.search(cap)
        if not m:
            continue
        value = float(m.group(1))
        observed["cumulative"] = value
        says_short = bool(_SHORT_WORDS.search(cap))
        looks_bearish = (
            (direction or "").strip().lower() == "short"
            or (losses is not None and wins is not None and losses > wins)
            or bool(_FELL_WORDS.search(cap)))
        if value > 0 and looks_bearish and not says_short:
            _issue(errors, "CUMULATIVE_SIGN_UNEXPLAINED",
                   f"caption reports {value:+.1f}% on a pattern that fell; "
                   f"short-side accounting must be stated in the caption")
        if value < 0 and says_short:
            warnings.append({
                "code": "CUMULATIVE_NEGATIVE_SHORT",
                "detail": f"short-side cumulative is {value:+.1f}%"})

    # ---- 5. citations must resolve inside the rendered sources list -----
    sm = _SOURCES.search(html)
    n_sources = len(re.findall(r"<li\b", sm.group(1), re.I)) if sm else 0
    body_html = _SOURCES.sub(" ", html)
    cited = {int(x) for x in re.findall(
        r"<sup[^>]*>\s*\[?(\d{1,3})\]?\s*</sup>", body_html, re.I)}
    orphans = sorted(c for c in cited if c > n_sources or c < 1)
    if orphans:
        _issue(errors, "CITATION_ORPHAN",
               f"citations {orphans} exceed the {n_sources}-item sources list")
    observed["sources"] = n_sources

    return {"ok": not errors, "errors": errors,
            "warnings": warnings, "observed": observed}
